# This is a basic workflow to help you get started with Actions

name: Netlify builds

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  repository_dispatch:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with: 
          version: 12.x
          

      # Runs a set of commands using the runners shell
      - name: Build site
        working-directory: ./gatsby-blog
        run: |
          yarn install --production
          yarn build
          
      - name: Netlify deployment      
        uses: nwtgck/actions-netlify@v1.1.11      
        with:
          publish-dir: './gatsby-blog/public'
          production-branch: main 
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
